In [1]:
from ultralytics import YOLO

MYMODEL_PATH = 'D:\\Work_space\\Projects\\AI-Game\\The_King_of_Fighters_XV\\model\\best.pt'

In [2]:
model = YOLO(MYMODEL_PATH)

In [3]:
import cv2
data = cv2.imread(MYMODEL_PATH)
print(type(data))

<class 'NoneType'>


In [4]:
result = model("./example/frame1870.jpg")


image 1/1 d:\Work_space\Projects\AI-Game\The_King_of_Fighters_XV\yolo\example\frame1870.jpg: 384x640 1 Jing, 1 Ann, 49.0ms
Speed: 3.5ms preprocess, 49.0ms inference, 5.9ms postprocess per image at shape (1, 3, 640, 640)


In [5]:
print(result[0])

ultralytics.yolo.engine.results.Results object with attributes:

boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes']
masks: None
names: {0: 'Jing', 1: 'Ann'}
orig_img: array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)


In [18]:
print(result[0].boxes.xyxy.shape[0])
print(result[0].boxes.cls)
cls_result = result[0].boxes.cls
xyxy_bbox_result = result[0].boxes.xyxy
print(result[0].boxes)

WARNING  'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.


2
tensor([1., 0.], device='cuda:0')
ultralytics.yolo.engine.results.Boxes object with attributes:

boxes: tensor([[1.3788e+03, 4.7728e+02, 1.6835e+03, 9.9131e+02, 9.3179e-01, 1.0000e+00],
        [1.0308e+03, 4.7774e+02, 1.3627e+03, 9.8889e+02, 9.1345e-01, 0.0000e+00]], device='cuda:0')
cls: tensor([1., 0.], device='cuda:0')
conf: tensor([0.9318, 0.9135], device='cuda:0')
data: tensor([[1.3788e+03, 4.7728e+02, 1.6835e+03, 9.9131e+02, 9.3179e-01, 1.0000e+00],
        [1.0308e+03, 4.7774e+02, 1.3627e+03, 9.8889e+02, 9.1345e-01, 0.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (1080, 1920)
shape: torch.Size([2, 6])
xywh: tensor([[1531.1613,  734.2946,  304.6799,  514.0245],
        [1196.7968,  733.3171,  331.9045,  511.1462]], device='cuda:0')
xywhn: tensor([[0.7975, 0.6799, 0.1587, 0.4759],
        [0.6233, 0.6790, 0.1729, 0.4733]], device='cuda:0')
xyxy: tensor([[1378.8213,  477.2823, 1683.5012,  991.3068],
        [1030.8445,  477.7440, 1362.7490,  988.8903]], devic

In [16]:
if cls_result[0] != cls_result[1]:
    print("jh")

In [10]:
# 0是ai，1是敌人
import torch

# 获得Ann和Jing的bbox的索引
Ann_index = torch.nonzero(cls_result)
Jing_index = torch.nonzero(cls_result==0)

# 获得Ann和JIng的bbox (xyxy格式)
Ann_bbox = xyxy_bbox_result[Ann_index][0].view([4])
Jing_bbox = xyxy_bbox_result[Jing_index][0].view([4])

# 计算Ann和Jing之间的距离（以Jing为原点，直接计算差值并取平均值），正数的话就是ann在右，负数的话就是ann在左
distance = torch.sum(Ann_bbox-Jing_bbox) / 2

print(Ann_bbox)
print(Jing_bbox)
print(distance.view([1]))

tensor([1378.8213,  477.2823, 1683.5012,  991.3068], device='cuda:0')
tensor([1030.8445,  477.7440, 1362.7490,  988.8903], device='cuda:0')
tensor([335.3419], device='cuda:0')
