In [10]:
from ultralytics import YOLO

MYMODEL_PATH = 'D:\\Work_space\\Projects\\AI-Game\\The_King_of_Fighters_XV\\model\\best.pt'

In [11]:
model = YOLO(MYMODEL_PATH)

In [12]:
import cv2
data = cv2.imread(MYMODEL_PATH)
print(type(data))

<class 'NoneType'>


In [13]:
result = model("./example/frame1870.jpg")


image 1/1 d:\Work_space\Projects\AI-Game\The_King_of_Fighters_XV\yolo\example\frame1870.jpg: 384x640 1 Jing, 1 Ann, 24.4ms
Speed: 2.0ms preprocess, 24.4ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)


In [14]:
print(result[0])

ultralytics.yolo.engine.results.Results object with attributes:

boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes']
masks: None
names: {0: 'Jing', 1: 'Ann'}
orig_img: array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)


In [15]:
print(result[0].boxes.xyxy)
print(result[0].boxes.cls)
cls_result = result[0].boxes.cls
xyxy_bbox_result = result[0].boxes.xyxy

tensor([[1378.8213,  477.2823, 1683.5012,  991.3068],
        [1030.8445,  477.7440, 1362.7490,  988.8903]], device='cuda:0')
tensor([1., 0.], device='cuda:0')


In [17]:
# 0是ai，1是敌人
import torch

# 获得Ann和Jing的bbox的索引
Ann_index = torch.nonzero(cls_result)
Jing_index = torch.nonzero(cls_result==0)

# 获得Ann和JIng的bbox (xyxy格式)
Ann_bbox = xyxy_bbox_result[Ann_index].view([4])
Jing_bbox = xyxy_bbox_result[Jing_index].view([4])

# 计算Ann和Jing之间的距离（以Jing为原点，直接计算差值并取平均值），正数的话就是ann在右，负数的话就是ann在左
distance = torch.sum(Ann_bbox-Jing_bbox) / 2

print(Ann_bbox)
print(Jing_bbox)
print(distance.view([1]))

tensor([1378.8213,  477.2823, 1683.5012,  991.3068], device='cuda:0')
tensor([1030.8445,  477.7440, 1362.7490,  988.8903], device='cuda:0')
tensor([335.3419], device='cuda:0')
